# Generated by Django 6.0 on 2025-12-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemnoticia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
